### ISSUE TITLE
Deprecate and archive this project

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/kubespark-operator#23]
given the work happening in https://github.com/radanalyticsio/spark-operator, and issues of confusion like https://github.com/radanalyticsio/spark-operator/issues/116, i think we should archive this project and make it clear that it is deprecated.

**Comment by elmiko** [comment]
before moving forward, i would love to get input from @mattf @willb and @tmckayus

**Comment by willb** [comment]
👍 strong agree!

**Comment by erikerlandson** [comment]
+1, makes sense to me
